-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.atividade
(
    "atvID" integer NOT NULL,
    academico_email "char",
    instituicao "char",
    disciplina "char",
    "numQuest" integer,
    "caminhoArquivo" "char",
    PRIMARY KEY ("atvID")
);

CREATE TABLE IF NOT EXISTS public.academico
(
    email "char" NOT NULL,
    nome "char" NOT NULL,
    instituicao "char",
    PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS public.lista
(
    gabarito boolean DEFAULT false,
    "atvID" integer NOT NULL,
    PRIMARY KEY ("atvID")
);

CREATE TABLE IF NOT EXISTS public.prova
(
    tipo integer DEFAULT 1,
    "atvID" integer NOT NULL,
    PRIMARY KEY ("atvID")
);

CREATE TABLE IF NOT EXISTS public.pesquisa
(
    "atvID_atividade" integer NOT NULL,
    email_academico "char" NOT NULL,
    PRIMARY KEY ("atvID_atividade", email_academico)
);

CREATE TABLE IF NOT EXISTS public.materias
(
    materia "char" NOT NULL,
    "atvID" integer NOT NULL,
    PRIMARY KEY (materia, "atvID")
);

ALTER TABLE IF EXISTS public.atividade
    ADD CONSTRAINT "ENVIA" FOREIGN KEY (academico_email)
    REFERENCES public.academico (email) MATCH FULL
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.lista
    ADD FOREIGN KEY ("atvID")
    REFERENCES public.atividade ("atvID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pesquisa
    ADD CONSTRAINT pesquisada FOREIGN KEY ("atvID_atividade")
    REFERENCES public.atividade ("atvID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pesquisa
    ADD CONSTRAINT pesquisa FOREIGN KEY (email_academico)
    REFERENCES public.academico (email) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.materias
    ADD FOREIGN KEY ("atvID")
    REFERENCES public.atividade ("atvID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;